theme: jekyll-theme-cayman
title: "CS 294/194-280 <br> Advanced Large Language Model Agents"
description: Spring 2025
show_downloads: false
github:
  is_project_page: false
plugins:
  - jekyll-redirect-from
